<?php require_once __DIR__ . '/functions.php';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';
    $id = (int)($_POST['product_id'] ?? 0);
    if ($action === 'add' && $id > 0 && product($id)) $_SESSION['cart'][$id] = min(20, (int)($_SESSION['cart'][$id] ?? 0) + 1);
    if ($action === 'remove') unset($_SESSION['cart'][$id]);
    if ($action === 'update') { foreach (($_POST['qty'] ?? []) as $pid => $qty) { $qty = max(0, min(20, (int)$qty)); if ($qty === 0) unset($_SESSION['cart'][(int)$pid]); else $_SESSION['cart'][(int)$pid] = $qty; } }
    redirect('cart.php');
}
$rows=[]; foreach(cart() as $id=>$qty) if($p=product((int)$id)) $rows[]=['p'=>$p,'qty'=>(int)$qty];
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>السلة | نُقطة</title><link rel="stylesheet" href="assets/style.css"></head><body><header class="container nav"><a class="logo" href="index.php">نُقطة <span>•</span></a><a class="cart" href="index.php">متابعة التسوق</a></header><main class="container" style="padding:30px 0 80px"><div class="section-head"><div><h1>سلة مشترياتك</h1><p><?= cartCount() ?> قطعة مختارة</p></div></div><?php if(!$rows): ?><div class="empty"><h2>السلة فارغة</h2><p>أضف شيئًا لطيفًا لتبدأ طلبك.</p><a class="btn" href="index.php">اكتشف المنتجات</a></div><?php else: ?><form method="post"><input type="hidden" name="action" value="update"><div class="grid" style="grid-template-columns:1fr 1fr"><?php foreach($rows as $row): $p=$row['p']; ?><article class="product"><div class="product-visual" style="background:<?= e($p['accent']) ?>"><span class="product-emoji"><?= e($p['emoji']) ?></span></div><div class="product-body"><h3><?= e($p['name']) ?></h3><p><?= money((int)$p['price']) ?> للقطعة</p><label>الكمية <input style="width:80px;padding:8px;border:1px solid var(--line);border-radius:8px" type="number" min="0" max="20" name="qty[<?= (int)$p['id'] ?>]" value="<?= $row['qty'] ?>"></label><button class="filter" style="margin-top:12px" formaction="cart.php" name="action" value="remove" type="submit">حذف</button></div></article><?php endforeach; ?></div><div class="summary"><strong>الإجمالي: <?= money(cartTotal()) ?></strong><br><small>يتم احتساب الشحن عند التواصل لتأكيد الطلب.</small></div><button class="btn" type="submit">تحديث السلة</button> <a class="btn" href="checkout.php">إتمام الطلب</a></form><?php endif; ?></main><footer><div class="container">نُقطة · تفاصيل صغيرة ليوم أجمل.</div></footer></body></html>
