<?php require_once __DIR__ . '/functions.php';
if (cartCount() === 0) redirect('cart.php');
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $name = trim($_POST['customer_name'] ?? ''); $phone = trim($_POST['phone'] ?? ''); $city = trim($_POST['city'] ?? ''); $address = trim($_POST['address'] ?? ''); $notes = trim($_POST['notes'] ?? '');
    if (mb_strlen($name)<2 || mb_strlen($phone)<8 || mb_strlen($city)<2 || mb_strlen($address)<5) $error='يرجى تعبئة البيانات المطلوبة بشكل صحيح.';
    else { try { db()->beginTransaction(); $total=cartTotal(); $stmt=db()->prepare('INSERT INTO orders (customer_name,phone,city,address,notes,total) VALUES (?,?,?,?,?,?)'); $stmt->execute([$name,$phone,$city,$address,$notes ?: null,$total]); $orderId=(int)db()->lastInsertId(); $itemStmt=db()->prepare('INSERT INTO order_items (order_id,product_id,product_name,unit_price,quantity) VALUES (?,?,?,?,?)'); foreach(cart() as $id=>$qty){$p=product((int)$id); if($p) $itemStmt->execute([$orderId,$p['id'],$p['name'],$p['price'],$qty]);} db()->commit(); $_SESSION['cart']=[]; redirect('success.php?id='.$orderId); } catch(Throwable $e) { if(db()->inTransaction()) db()->rollBack(); $error='تعذر حفظ الطلب حاليًا. تحقق من إعداد قاعدة البيانات.'; } }
}
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>إتمام الطلب | نُقطة</title><link rel="stylesheet" href="assets/style.css"></head><body><header class="container nav"><a class="logo" href="index.php">نُقطة <span>•</span></a><a class="cart" href="cart.php">العودة للسلة</a></header><main class="container"><div class="form-wrap"><h1>آخر خطوة</h1><p>اترك بياناتك وسنتواصل معك لتأكيد الطلب والتوصيل.</p><?php if($error): ?><div class="summary" style="color:#a34b36"><?= e($error) ?></div><?php endif; ?><form method="post"><div class="form-grid"><div class="field"><label>الاسم الكامل *</label><input required name="customer_name" value="<?= e($_POST['customer_name']??'') ?>"></div><div class="field"><label>رقم الجوال *</label><input required name="phone" type="tel" value="<?= e($_POST['phone']??'') ?>"></div><div class="field"><label>المدينة *</label><input required name="city" value="<?= e($_POST['city']??'') ?>"></div><div class="field"><label>العنوان المختصر *</label><input required name="address" value="<?= e($_POST['address']??'') ?>"></div><div class="field full"><label>ملاحظات إضافية</label><textarea name="notes"><?= e($_POST['notes']??'') ?></textarea></div></div><div class="summary"><strong>إجمالي الطلب: <?= money(cartTotal()) ?></strong></div><button class="btn" type="submit">إرسال الطلب</button></form></div></main><footer><div class="container">نُقطة · سنتواصل معك لتأكيد الطلب.</div></footer></body></html>
